name: hendrix_marketplace
description: An App

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: "^0.1.3"
  firebase_auth: "^0.18.2"
#  cloud_firestore: "^0.12.9+5"
  firebase_core: "^0.5.1"
  firebase_analytics: "^5.0.2"
  firebase_database: "^4.2.0"
  provider: "^4.3.2+2"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icon/ 

